version: '3.1'

services:
  client:
      build: './client'
      volumes:
        - './client:/home/node/app'
      working_dir: '/home/node/app'
      command: 'yarn serve'
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:8000:8000
      environment:
      - CHOKIDAR_USEPOLLING=true